### ISSUE TITLE
unable to use `Settings::all()` on larave 9.5 and package v2.2.2

### ISSUE THREAD

**Issue by josiahke** [rawilk/laravel-settings#43]
### Laravel Settings

2.2.2

### Laravel Version

9.52

### Bug description

unable to use `Settings::all()`
unable to install v3 on Laravel 9

**Comment by dnkmdg** [comment]
I experience the same issue - with following response: 

`Md5KeyGenerator does not support removing the context from the key`

Pointing to `/vendor/rawilk/laravel-settings/src/Settings.php:203-216`

![image](https://github.com/rawilk/laravel-settings/assets/6313551/748742ef-8db2-4a06-80a0-474927c6c57f)

**Comment by rawilk** [comment]
The `all()` method was introduced with in v3. Due to how v2 handles setting keys, I can't think of a way to make it available for v2 without it introducing a breaking change.

**Comment by rawilk** [comment]
@dnkmdg The default `Md5KeyGenerator` is not allowed to be used for retrieving all settings; you need to use the `ReadableKeyGenerator` instead, or a custom key generator, which can be set on the `key_generator` configuration key in `config/settings.php`.

If this isn't clear in the docs, I may need to update them to better explain this.

For more information on this, please see: https://randallwilk.dev/docs/laravel-settings/v3/advanced-usage/custom-generators#user-content-keygenerator

**Comment by rawilk** [comment]
Hey, I'm going to close this issue since there hasn't been any activity on it for a little while. Feel free to re-open the issue if you still need help.
