### ISSUE TITLE
how can I store key and value without any modification like md5?

### ISSUE THREAD

**Issue by matiazar** [rawilk/laravel-settings#53]
### Laravel Settings

v3

### Laravel Version

v10

### Bug description

how can I store key and value without any modification like md5?
please.

**Comment by matiazar** [comment]
I found how to disable decryotion.. now I need to disable serialization. I need only a value. thanks

**Comment by rawilk** [comment]
Please refer to the [docs](https://randallwilk.dev/docs/laravel-settings/v3/advanced-usage/custom-generators#user-content-keygenerator) for this.

There is already a built-in key generator, called the `ReadableKeyGenerator`, that will not use md5 on the setting keys. You just need to configure the package to use this one instead in the config file.

**Comment by matiazar** [comment]
yes I used it,. but now I want to make the value clean.. store the value I send.. only text or number

thanks

**Comment by rawilk** [comment]
What do you mean by "make the value clean"? If you don't want the value encrypted, you can disable that in the config. You can also use a custom value serializer, similar to how the key generators work, to prevent the value from being serialized or json_encoded before storing it.

**Comment by rawilk** [comment]
I'm going to close this issue since it hasn't had any activity in a while. Feel free to re-open in the future if necessary.
